import { ArrowLeft, LockKeyhole, Mail, Store, UserRound } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { useState } from 'react'
import { supabase, supabaseEnabled } from '../lib/supabase'
import { resolveAccount } from '../lib/account'

export default function LoginPage(){
  const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[busy,setBusy]=useState(false);const nav=useNavigate()
  const submit=async e=>{e.preventDefault();if(!supabaseEnabled){nav('/owner');return}setBusy(true);try{const{error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;const acc=await resolveAccount();if(acc.account_type==='admin')nav('/owner');else if(acc.account_type==='customer')nav('/account');else{await supabase.auth.signOut();throw new Error('Akun belum terhubung ke toko ini.')}}catch(e){alert(e.message)}finally{setBusy(false)}}
  return <div className="auth-page auth-page-v2"><div className="auth-card"><Link to="/" className="auth-brand"><span>iM</span><div><b>iMersWAStore</b><small>Single Store Commerce</small></div></Link><span className="auth-kicker">AKUN & DASHBOARD</span><h1>Selamat Datang Kembali</h1><p>Satu halaman login untuk owner/staff dan pelanggan terdaftar.</p><form onSubmit={submit}><label><span><Mail/> Email</span><input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="email@toko.com"/></label><label><span><LockKeyhole/> Password</span><input type="password" required={supabaseEnabled} value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••"/></label><div className="auth-row"><label className="auth-check"><input type="checkbox"/> Ingat saya</label><Link to="/forgot-password">Lupa password?</Link></div><button className="btn-primary full large" disabled={busy}>{busy?'Masuk...':supabaseEnabled?'Masuk':'Buka Demo Dashboard'}</button></form><div className="auth-register-box"><UserRound/><div><b>Belum punya akun pelanggan?</b><span>Daftar tanpa membuat toko baru.</span></div><Link to="/register">Daftar</Link></div>{!supabaseEnabled&&<div className="auth-note">Mode demo aktif karena <code>.env</code> Supabase belum diisi.</div>}<div className="auth-links"><Link to="/"><ArrowLeft size={14}/> Kembali ke toko</Link><span><Store size={14}/> Single Store</span></div></div></div>
}
