import DashboardShell from '../components/DashboardShell'
import { useEffect, useMemo, useState } from 'react'
import { getOwnerContext, supabase, supabaseEnabled } from '../lib/supabase'
import { rupiah } from '../lib/format'
import { Minus, Plus, Search, ShoppingCart, Trash2 } from 'lucide-react'

export default function OwnerPOS(){
  const[products,setProducts]=useState([]);const[categories,setCategories]=useState([]);const[search,setSearch]=useState('');const[category,setCategory]=useState('all');const[page,setPage]=useState(1);const[size,setSize]=useState(12);const[cart,setCart]=useState([]);const[customer,setCustomer]=useState({name:'',phone:''});const[payment,setPayment]=useState('cash');const[notes,setNotes]=useState('');const[busy,setBusy]=useState(false);const[lastOrder,setLastOrder]=useState(null)
  useEffect(()=>{if(!supabaseEnabled)return;(async()=>{const ctx=await getOwnerContext();if(!ctx.storeId)throw new Error('Store tidak ditemukan.');const[p,c]=await Promise.all([supabase.from('products').select('id,name,price,stock,type,cover_image,category_id,status').eq('store_id',ctx.storeId).eq('status',true).order('name'),supabase.from('categories').select('id,name,status').eq('store_id',ctx.storeId).eq('status',true).order('name')]);if(p.error)throw p.error;if(c.error)throw c.error;setProducts(p.data||[]);setCategories(c.data||[])})().catch(e=>alert(e.message))},[])
  const filtered=useMemo(()=>products.filter(p=>(category==='all'||p.category_id===category)&&(!search||p.name.toLowerCase().includes(search.toLowerCase()))),[products,category,search]);const pages=Math.max(1,Math.ceil(filtered.length/size));const rows=filtered.slice((page-1)*size,page*size)
  const add=p=>setCart(prev=>{const hit=prev.find(x=>x.id===p.id);if(hit)return prev.map(x=>x.id===p.id?{...x,qty:x.qty+1}:x);return[...prev,{...p,qty:1}]})
  const qty=(id,n)=>setCart(prev=>prev.map(x=>x.id===id?{...x,qty:Math.max(1,n)}:x));const remove=id=>setCart(prev=>prev.filter(x=>x.id!==id));const total=cart.reduce((n,x)=>n+Number(x.price||0)*x.qty,0)
  const checkout=async()=>{if(!cart.length)return alert('Keranjang POS masih kosong.');setBusy(true);try{const{data,error}=await supabase.rpc('create_pos_order',{p_items:cart.map(x=>({product_id:x.id,qty:x.qty})),p_customer:{name:customer.name||'Customer POS',phone:customer.phone||null},p_payment_method:payment,p_notes:notes||null});if(error)throw error;setLastOrder(data);setCart([]);setCustomer({name:'',phone:''});setNotes('');const ids=products.map(x=>x.id);if(ids.length){const{data:ref}=await supabase.from('products').select('id,stock').in('id',ids);if(ref)setProducts(v=>v.map(p=>({...p,stock:ref.find(r=>r.id===p.id)?.stock??p.stock})))}}catch(e){alert(e.message)}finally{setBusy(false)}}
  return <DashboardShell title="Kasir POS" subtitle="Transaksi langsung toko/offline memakai katalog dan stok Supabase yang sama.">
    {lastOrder&&<div className="module-note">Transaksi berhasil: <b>{lastOrder.order_number||lastOrder.id}</b> — Total {rupiah(lastOrder.total_amount||0)}</div>}
    <div className="pos-layout"><section><div className="toolbar"><div className="search-small"><Search/><input placeholder="Cari produk..." value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/></div><select value={category} onChange={e=>{setCategory(e.target.value);setPage(1)}}><option value="all">Semua kategori</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select value={size} onChange={e=>{setSize(Number(e.target.value));setPage(1)}}><option value="12">12 / halaman</option><option value="24">24 / halaman</option><option value="48">48 / halaman</option></select></div>
      <div className="pos-product-grid">{rows.map(p=><button className="pos-product" key={p.id} onClick={()=>add(p)} disabled={p.type==='physical'&&Number(p.stock||0)<=0}><img src={p.cover_image||'https://placehold.co/300x180?text=Produk'} /><div><b>{p.name}</b><strong>{rupiah(p.price)}</strong><small style={{display:'block',marginTop:4,color:'var(--admin-muted)'}}>{p.type==='physical'?`Stok ${p.stock}`:p.type}</small></div></button>)}</div>
      <div className="pagination" style={{marginTop:12,border:'1px solid var(--admin-border)',borderRadius:12}}><span>{filtered.length} produk</span><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>←</button><b>{page}/{pages}</b><button disabled={page>=pages} onClick={()=>setPage(p=>p+1)}>→</button></div></section>
      <aside className="dash-panel pos-cart"><div className="panel-head"><div><h2><ShoppingCart size={16}/> Keranjang POS</h2><p>{cart.length} item berbeda</p></div></div>{cart.length===0?<div className="empty-cell">Klik produk untuk menambah ke keranjang.</div>:cart.map(x=><div className="pos-cart-row" key={x.id}><div><b>{x.name}</b><small>{rupiah(x.price)} × {x.qty}</small><div style={{display:'flex',gap:5,marginTop:6}}><button className="btn-outline" onClick={()=>qty(x.id,x.qty-1)}><Minus size={12}/></button><button className="btn-outline" onClick={()=>qty(x.id,x.qty+1)}><Plus size={12}/></button><button className="btn-outline" onClick={()=>remove(x.id)}><Trash2 size={12}/></button></div></div><strong>{rupiah(Number(x.price||0)*x.qty)}</strong></div>)}
        <div className="pos-total"><span>Total</span><strong>{rupiah(total)}</strong></div><div className="stack-form"><label>Nama Customer<input value={customer.name} onChange={e=>setCustomer({...customer,name:e.target.value})}/></label><label>WhatsApp<input value={customer.phone} onChange={e=>setCustomer({...customer,phone:e.target.value})}/></label><label>Metode Pembayaran<select value={payment} onChange={e=>setPayment(e.target.value)}><option value="cash">Cash / Lunas</option><option value="transfer">Transfer</option><option value="qris">QRIS</option><option value="card">Debit / Credit</option></select></label><label>Catatan<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label><button className="btn-primary" onClick={checkout} disabled={busy||!cart.length}>{busy?'Memproses...':'Selesaikan Transaksi'}</button></div>
      </aside></div>
  </DashboardShell>
}
