import { appConfirm } from '../lib/appDialog'
import DashboardShell from '../components/DashboardShell'
import { useEffect, useMemo, useState } from 'react'
import { getOwnerContext, supabase, supabaseEnabled } from '../lib/supabase'
import { Banknote, CreditCard, Edit3, Plus, QrCode, Search, Trash2, WalletCards, X } from 'lucide-react'

const empty={payment_type:'bank',provider_name:'',account_name:'',account_number:'',qr_image:'',instructions:'',icon_url:'',sort_order:0,enabled:true}
const typeLabel={bank:'Transfer Bank',ewallet:'E-Wallet',qris:'QRIS',cod:'COD / Tunai'}
const typeHelp={bank:'Rekening bank untuk transfer manual',ewallet:'GoPay, DANA, OVO, ShopeePay, dll.',qris:'QRIS statis dengan gambar QR',cod:'Bayar tunai saat transaksi / pickup'}

export default function OwnerPayments(){
 const[data,setData]=useState([]),[storeId,setStoreId]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState(1),[size,setSize]=useState(10),[modal,setModal]=useState(false),[form,setForm]=useState(empty),[busy,setBusy]=useState(false)
 const load=async()=>{if(!supabaseEnabled)return;const ctx=await getOwnerContext();if(!ctx.storeId)throw new Error('Store tidak ditemukan');setStoreId(ctx.storeId);const{data,error}=await supabase.from('payment_settings').select('*').eq('store_id',ctx.storeId).order('sort_order').order('created_at');if(error)throw error;setData(data||[])}
 useEffect(()=>{load().catch(e=>alert(e.message))},[])
 const filtered=useMemo(()=>data.filter(x=>!search||`${x.provider_name||''} ${x.account_name||''} ${x.account_number||''} ${x.payment_type||''}`.toLowerCase().includes(search.toLowerCase())),[data,search]);const pages=Math.max(1,Math.ceil(filtered.length/size)),safePage=Math.min(page,pages),rows=filtered.slice((safePage-1)*size,safePage*size)
 const save=async e=>{e.preventDefault();setBusy(true);try{const payload={store_id:storeId,payment_type:form.payment_type,provider_name:form.provider_name||typeLabel[form.payment_type],account_name:['bank','ewallet','qris'].includes(form.payment_type)?(form.account_name||null):null,account_number:['bank','ewallet'].includes(form.payment_type)?(form.account_number||null):null,qr_image:form.payment_type==='qris'?(form.qr_image||null):null,instructions:form.instructions||null,icon_url:form.icon_url||null,sort_order:Number(form.sort_order||0),enabled:!!form.enabled,metadata:{}};const q=form.id?supabase.from('payment_settings').update(payload).eq('id',form.id).eq('store_id',storeId):supabase.from('payment_settings').insert(payload);const{error}=await q;if(error)throw error;await load();setModal(false);setForm(empty)}catch(e){alert(e.message)}finally{setBusy(false)}}
 const del=async x=>{if(!(await appConfirm(`Hapus metode ${x.provider_name||x.payment_type}?`)))return;const{error}=await supabase.from('payment_settings').delete().eq('id',x.id).eq('store_id',storeId);if(error)alert(error.message);else load().catch(e=>alert(e.message))}
 const icon=t=>t==='qris'?<QrCode/>:t==='ewallet'?<WalletCards/>:t==='cod'?<Banknote/>:<CreditCard/>
 const chooseType=payment_type=>setForm(f=>({...f,payment_type,provider_name:f.id?f.provider_name:(payment_type==='cod'?'COD / Tunai':''),account_name:payment_type==='cod'?'':f.account_name,account_number:['qris','cod'].includes(payment_type)?'':f.account_number,qr_image:payment_type==='qris'?f.qr_image:''}))
 const openNew=()=>{setForm(empty);setModal(true)}
 const openEdit=x=>{setForm({...empty,...x});setModal(true)}
 const providerTitle=form.provider_name||typeLabel[form.payment_type]
 return <DashboardShell title="Pembayaran & Rekening" subtitle="Kelola rekening bank, e-wallet, QRIS dan COD yang tampil di checkout.">
  <div className="module-hero tone-payment"><div><span>PAYMENT CENTER</span><h2>Metode pembayaran yang jelas untuk pelanggan</h2><p>Tambah beberapa rekening, e-wallet, QRIS atau COD. Hanya metode aktif yang ditampilkan saat checkout.</p></div><div className="module-hero-icon"><WalletCards/></div></div>
  <div className="toolbar"><div className="search-small"><Search/><input placeholder="Cari bank, provider atau rekening..." value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/></div><div className="toolbar-spacer"/><button className="btn-primary" onClick={openNew}><Plus size={15}/>Tambah Metode</button></div>
  <div className="dash-panel table-panel"><div className="responsive-table"><table><thead><tr><th>Metode</th><th>Atas Nama</th><th>Nomor / Detail</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{rows.length?rows.map(x=><tr key={x.id}><td><div className="table-product"><span className="payment-type-icon">{icon(x.payment_type)}</span><div><b>{x.provider_name||typeLabel[x.payment_type]}</b><small>{typeLabel[x.payment_type]||x.payment_type}</small></div></div></td><td>{x.account_name||'-'}</td><td>{x.payment_type==='qris'?(x.qr_image?'QRIS siap digunakan':'QR belum diisi'):x.payment_type==='cod'?(x.instructions||'Tunai'):(x.account_number||'-')}</td><td><span className={`status ${x.enabled?'ok':'off'}`}>{x.enabled?'Aktif':'Nonaktif'}</span></td><td className="table-actions"><button title="Edit" onClick={()=>openEdit(x)}><Edit3/></button><button title="Hapus" onClick={()=>del(x)}><Trash2/></button></td></tr>):<tr><td colSpan="5" className="empty-cell">Belum ada metode pembayaran. Klik “Tambah Metode” untuk mulai.</td></tr>}</tbody></table></div><div className="pagination"><span>{filtered.length} metode</span><select value={size} onChange={e=>{setSize(Number(e.target.value));setPage(1)}}><option>10</option><option>25</option><option>50</option></select><button disabled={safePage<=1} onClick={()=>setPage(p=>p-1)}>←</button><b>{safePage}/{pages}</b><button disabled={safePage>=pages} onClick={()=>setPage(p=>p+1)}>→</button></div></div>
  {modal&&<div className="modal-backdrop"><form className="admin-modal admin-modal-lg" onSubmit={save}>
    <div className="admin-modal-head"><div><h2>{form.id?'Edit':'Tambah'} Metode Pembayaran</h2><p>Pilih tipe pembayaran lalu lengkapi data yang benar-benar diperlukan.</p></div><button type="button" onClick={()=>setModal(false)}><X/></button></div>
    <div className="payment-type-picker">{['bank','ewallet','qris','cod'].map(t=><button key={t} type="button" className={`payment-type-option ${form.payment_type===t?'active':''}`} onClick={()=>chooseType(t)}><span>{icon(t)}</span><span><b>{typeLabel[t]}</b><small>{typeHelp[t]}</small></span></button>)}</div>
    <div className="payment-modal-layout"><div className="form-grid">
      <label className="span2">Nama Bank / Provider<input required value={form.provider_name||''} onChange={e=>setForm({...form,provider_name:e.target.value})} placeholder={form.payment_type==='bank'?'Contoh: BCA':form.payment_type==='ewallet'?'Contoh: GoPay':form.payment_type==='qris'?'Contoh: QRIS iMersWAStore':'COD / Tunai'}/></label>
      {form.payment_type!=='cod'&&<label>Atas Nama<input value={form.account_name||''} onChange={e=>setForm({...form,account_name:e.target.value})} placeholder="Nama pemilik rekening / merchant"/></label>}
      {['bank','ewallet'].includes(form.payment_type)&&<label>Nomor {form.payment_type==='bank'?'Rekening':'Wallet'}<input value={form.account_number||''} onChange={e=>setForm({...form,account_number:e.target.value})} placeholder={form.payment_type==='bank'?'1234567890':'62812...'}/></label>}
      {form.payment_type==='qris'&&<label className="span2">QRIS Image URL<input value={form.qr_image||''} onChange={e=>setForm({...form,qr_image:e.target.value})} placeholder="https://.../qris.png"/></label>}
      <label className="span2">Logo / Icon URL <small>Opsional. Bisa dipakai untuk logo bank atau e-wallet.</small><input value={form.icon_url||''} onChange={e=>setForm({...form,icon_url:e.target.value})} placeholder="https://.../logo.png"/></label>
      <label className="span2">Petunjuk Pembayaran<textarea value={form.instructions||''} onChange={e=>setForm({...form,instructions:e.target.value})} placeholder={form.payment_type==='qris'?'Contoh: Scan QRIS lalu simpan bukti pembayaran.':form.payment_type==='cod'?'Contoh: Pembayaran tunai saat pickup / barang diterima.':'Contoh: Transfer sesuai total pesanan lalu konfirmasi pembayaran.'}/></label>
      <label>Urutan<input type="number" min="0" value={form.sort_order||0} onChange={e=>setForm({...form,sort_order:e.target.value})}/></label><label>Status<select value={form.enabled?'yes':'no'} onChange={e=>setForm({...form,enabled:e.target.value==='yes'})}><option value="yes">Aktif</option><option value="no">Nonaktif</option></select></label>
    </div><aside className="payment-preview"><span>PREVIEW CHECKOUT</span><div className="payment-preview-card"><div><small>{typeLabel[form.payment_type]}</small><b>{providerTitle}</b></div>{form.payment_type==='qris'&&form.qr_image?<img className="payment-preview-qr" src={form.qr_image} alt="QRIS preview"/>:<strong>{form.account_number||form.account_name||typeHelp[form.payment_type]}</strong>}</div><p className="payment-help">Preview ini membantu memastikan nama provider, rekening dan QRIS terlihat jelas sebelum disimpan.</p></aside></div>
    <div className="modal-foot"><button type="button" className="btn-outline" onClick={()=>setModal(false)}>Batal</button><button className="btn-primary" disabled={busy}>{busy?'Menyimpan...':'Simpan Metode'}</button></div>
  </form></div>}
 </DashboardShell>
}
