import DashboardShell from '../components/DashboardShell'
import { useEffect, useMemo, useState } from 'react'
import { getOwnerContext, supabase, supabaseEnabled } from '../lib/supabase'
import { BadgeCheck, CheckCircle2, ExternalLink, Eye, Search, X, XCircle } from 'lucide-react'
import { rupiah } from '../lib/format'

export default function OwnerPaymentConfirmations(){
 const[data,setData]=useState([]),[storeId,setStoreId]=useState(''),[search,setSearch]=useState(''),[status,setStatus]=useState('all'),[page,setPage]=useState(1),[size,setSize]=useState(10),[review,setReview]=useState(null),[busy,setBusy]=useState(false)
 const load=async()=>{if(!supabaseEnabled)return;const ctx=await getOwnerContext();setStoreId(ctx.storeId);const{data,error}=await supabase.from('payment_confirmations').select('*,orders(id,order_number,total_amount,payment_status,status)').eq('store_id',ctx.storeId).order('created_at',{ascending:false});if(error)throw error;setData(data||[])}
 useEffect(()=>{load().catch(e=>alert(e.message))},[])
 const filtered=useMemo(()=>data.filter(x=>(status==='all'||x.status===status)&&(!search||`${x.orders?.order_number||''} ${x.payer_name||''} ${x.payer_phone||''}`.toLowerCase().includes(search.toLowerCase()))),[data,search,status]);const pages=Math.max(1,Math.ceil(filtered.length/size)),safePage=Math.min(page,pages),rows=filtered.slice((safePage-1)*size,safePage*size)
 const act=async(x,next)=>{setBusy(true);try{const{error}=await supabase.from('payment_confirmations').update({status:next,verified_at:new Date().toISOString()}).eq('id',x.id).eq('store_id',storeId);if(error)throw error;if(next==='verified'){const{error:oerr}=await supabase.from('orders').update({payment_status:'paid',updated_at:new Date().toISOString()}).eq('id',x.order_id).eq('store_id',storeId);if(oerr)throw oerr}await load();setReview(null)}catch(e){alert(e.message)}finally{setBusy(false)}}
 return <DashboardShell title="Konfirmasi Pembayaran" subtitle="Periksa bukti transfer pelanggan lalu sinkronkan status pembayaran order.">
  <div className="module-hero tone-confirmation"><div><span>PAYMENT VERIFICATION</span><h2>Verifikasi bukti bayar tanpa menebak-nebak</h2><p>Lihat bukti, nilai pembayaran dan data order dalam satu panel sebelum menerima atau menolak konfirmasi.</p></div><div className="module-hero-icon"><BadgeCheck/></div></div>
  <div className="toolbar"><div className="search-small"><Search/><input placeholder="Cari order, nama atau WhatsApp..." value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/></div><select className="filter-select" value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="all">Semua Status</option><option value="pending">Pending</option><option value="verified">Verified</option><option value="rejected">Rejected</option></select></div>
  <div className="dash-panel table-panel"><div className="responsive-table"><table><thead><tr><th>Order</th><th>Pembayar</th><th>Jumlah</th><th>Bukti</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{rows.length?rows.map(x=><tr key={x.id}><td><b>{x.orders?.order_number||'-'}</b><small>{new Date(x.created_at).toLocaleString('id-ID')}</small></td><td><b>{x.payer_name||'-'}</b><small>{x.payer_phone||'-'}</small></td><td><b>{rupiah(x.amount)}</b><small>Order {rupiah(x.orders?.total_amount||0)}</small></td><td>{x.proof_url?<a className="inline-link" target="_blank" rel="noreferrer" href={x.proof_url}><ExternalLink/> Lihat Bukti</a>:'-'}</td><td><span className={`status ${x.status==='verified'?'ok':x.status==='rejected'?'off':'warn'}`}>{x.status}</span></td><td className="table-actions wide"><button title="Periksa" onClick={()=>setReview(x)}><Eye/> Periksa</button>{x.status==='pending'&&<><button className="approve" title="Verifikasi" onClick={()=>setReview({...x,__action:'verified'})}><CheckCircle2/> Verifikasi</button><button className="reject" title="Tolak" onClick={()=>setReview({...x,__action:'rejected'})}><XCircle/> Tolak</button></>}</td></tr>):<tr><td colSpan="6" className="empty-cell">Belum ada konfirmasi pembayaran pada filter ini.</td></tr>}</tbody></table></div><div className="pagination"><span>{filtered.length} konfirmasi</span><select value={size} onChange={e=>{setSize(Number(e.target.value));setPage(1)}}><option>10</option><option>25</option><option>50</option></select><button disabled={safePage<=1} onClick={()=>setPage(p=>p-1)}>←</button><b>{safePage}/{pages}</b><button disabled={safePage>=pages} onClick={()=>setPage(p=>p+1)}>→</button></div></div>
  {review&&<div className="modal-backdrop"><div className="admin-modal admin-modal-lg"><div className="admin-modal-head"><div><h2>Periksa Pembayaran {review.orders?.order_number||''}</h2><p>Pastikan bukti dan nominal sesuai sebelum mengubah status pembayaran.</p></div><button type="button" onClick={()=>setReview(null)}><X/></button></div><div className="confirmation-layout"><div className="confirmation-proof">{review.proof_url?<a href={review.proof_url} target="_blank" rel="noreferrer"><img src={review.proof_url} alt="Bukti pembayaran"/></a>:<span>Tidak ada bukti pembayaran.</span>}</div><div><div className="confirmation-data"><div><span>Nomor Order</span><b>{review.orders?.order_number||'-'}</b></div><div><span>Nama Pembayar</span><b>{review.payer_name||'-'}</b></div><div><span>WhatsApp</span><b>{review.payer_phone||'-'}</b></div><div><span>Jumlah Dikonfirmasi</span><b>{rupiah(review.amount)}</b></div><div><span>Total Order</span><b>{rupiah(review.orders?.total_amount||0)}</b></div><div><span>Status Saat Ini</span><b>{review.status}</b></div></div>{review.proof_url&&<a className="inline-link" style={{marginTop:12}} href={review.proof_url} target="_blank" rel="noreferrer"><ExternalLink/> Buka bukti ukuran penuh</a>} {review.status==='pending'&&<div className="confirmation-actions"><button className="verify" disabled={busy} onClick={()=>act(review,'verified')}><CheckCircle2/> {busy?'Memproses...':'Verifikasi Pembayaran'}</button><button className="deny" disabled={busy} onClick={()=>act(review,'rejected')}><XCircle/> Tolak Konfirmasi</button></div>}</div></div><div className="modal-foot"><button className="btn-outline" onClick={()=>setReview(null)}>Tutup</button></div></div></div>}
 </DashboardShell>
}
