import DashboardShell from '../components/DashboardShell'
import { useEffect, useMemo, useState } from 'react'
import { getOwnerContext, supabase, supabaseEnabled } from '../lib/supabase'
import { rupiah } from '../lib/format'
import { Edit3, Plus, Search, Trash2, X } from 'lucide-react'

const empty={code:'',name:'',discount_type:'percent',discount_value:10,min_order:0,max_discount:'',start_at:'',end_at:'',usage_limit:'',active:true}
export default function OwnerCoupons(){
  const[data,setData]=useState([]);const[storeId,setStoreId]=useState('');const[search,setSearch]=useState('');const[page,setPage]=useState(1);const[size,setSize]=useState(10);const[modal,setModal]=useState(false);const[form,setForm]=useState(empty);const[busy,setBusy]=useState(false)
  const load=async()=>{if(!supabaseEnabled)return;const ctx=await getOwnerContext();if(!ctx.storeId)throw new Error('Store tidak ditemukan.');setStoreId(ctx.storeId);const{data,error}=await supabase.from('coupons').select('*').eq('store_id',ctx.storeId).order('created_at',{ascending:false});if(error)throw error;setData(data||[])}
  useEffect(()=>{load().catch(e=>alert(e.message))},[])
  const filtered=useMemo(()=>data.filter(x=>!search||`${x.code} ${x.name||''}`.toLowerCase().includes(search.toLowerCase())),[data,search]);const pages=Math.max(1,Math.ceil(filtered.length/size));const rows=filtered.slice((page-1)*size,page*size)
  const save=async e=>{e.preventDefault();setBusy(true);try{const payload={store_id:storeId,code:form.code.trim().toUpperCase(),name:form.name||null,discount_type:form.discount_type,discount_value:Number(form.discount_value||0),min_order:Number(form.min_order||0),max_discount:form.max_discount?Number(form.max_discount):null,start_at:form.start_at?new Date(form.start_at).toISOString():null,end_at:form.end_at?new Date(form.end_at).toISOString():null,usage_limit:form.usage_limit?Number(form.usage_limit):null,active:!!form.active};if(form.id){const{error}=await supabase.from('coupons').update(payload).eq('id',form.id).eq('store_id',storeId);if(error)throw error}else{const{error}=await supabase.from('coupons').insert(payload);if(error)throw error}await load();setModal(false)}catch(e){alert(e.message)}finally{setBusy(false)}}
  const del=async x=>{if(!confirm(`Hapus kupon ${x.code}?`))return;const{error}=await supabase.from('coupons').delete().eq('id',x.id).eq('store_id',storeId);if(error)alert(error.message);else load().catch(e=>alert(e.message))}
  const label=x=>x.discount_type==='percent'?`${x.discount_value}%`:rupiah(x.discount_value)
  return <DashboardShell title="Kupon & Promo" subtitle="Kelola kode promo untuk toko ini. Engine validasi kupon terhubung ke checkout Supabase.">
    <div className="toolbar"><div className="search-small"><Search/><input placeholder="Cari kode / nama kupon..." value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/></div><div className="toolbar-spacer"/><button className="btn-primary" onClick={()=>{setForm(empty);setModal(true)}}><Plus size={15}/>Buat Kupon</button></div>
    <div className="dash-panel table-panel"><div className="responsive-table"><table><thead><tr><th>Kode</th><th>Nama</th><th>Diskon</th><th>Min Order</th><th>Pemakaian</th><th>Periode</th><th>Status</th><th></th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><b>{x.code}</b></td><td>{x.name||'-'}</td><td><span className="soft-pill">{label(x)}</span></td><td>{rupiah(x.min_order)}</td><td>{x.usage_count||0}{x.usage_limit?` / ${x.usage_limit}`:''}</td><td>{x.start_at?new Date(x.start_at).toLocaleDateString('id-ID'):'-'} — {x.end_at?new Date(x.end_at).toLocaleDateString('id-ID'):'∞'}</td><td><span className={`status ${x.active?'ok':'off'}`}>{x.active?'Aktif':'Nonaktif'}</span></td><td className="table-actions"><button onClick={()=>{setForm({...empty,...x,start_at:x.start_at?x.start_at.slice(0,16):'',end_at:x.end_at?x.end_at.slice(0,16):''});setModal(true)}}><Edit3/></button><button onClick={()=>del(x)}><Trash2/></button></td></tr>)}</tbody></table></div><div className="pagination"><span>{filtered.length} data</span><select value={size} onChange={e=>{setSize(Number(e.target.value));setPage(1)}}><option>10</option><option>25</option><option>50</option></select><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>←</button><b>{page}/{pages}</b><button disabled={page>=pages} onClick={()=>setPage(p=>p+1)}>→</button></div></div>
    {modal&&<div className="modal-backdrop"><form className="admin-modal" onSubmit={save}><div className="admin-modal-head"><div><h2>{form.id?'Edit':'Buat'} Kupon</h2><p>Kode kupon unik untuk toko ini.</p></div><button type="button" onClick={()=>setModal(false)}><X/></button></div><div className="form-grid"><label>Kode<input required value={form.code} onChange={e=>setForm({...form,code:e.target.value.toUpperCase().replace(/\s+/g,'')})}/></label><label>Nama Promo<input value={form.name||''} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Tipe Diskon<select value={form.discount_type} onChange={e=>setForm({...form,discount_type:e.target.value})}><option value="percent">Persen</option><option value="fixed">Nominal</option></select></label><label>Nilai Diskon<input type="number" min="0" value={form.discount_value} onChange={e=>setForm({...form,discount_value:e.target.value})}/></label><label>Minimum Order<input type="number" min="0" value={form.min_order} onChange={e=>setForm({...form,min_order:e.target.value})}/></label><label>Maks Diskon<input type="number" min="0" value={form.max_discount||''} onChange={e=>setForm({...form,max_discount:e.target.value})} placeholder="Kosong = tanpa batas"/></label><label>Mulai<input type="datetime-local" value={form.start_at||''} onChange={e=>setForm({...form,start_at:e.target.value})}/></label><label>Berakhir<input type="datetime-local" value={form.end_at||''} onChange={e=>setForm({...form,end_at:e.target.value})}/></label><label>Limit Pemakaian<input type="number" min="1" value={form.usage_limit||''} onChange={e=>setForm({...form,usage_limit:e.target.value})}/></label><label>Status<select value={form.active?'yes':'no'} onChange={e=>setForm({...form,active:e.target.value==='yes'})}><option value="yes">Aktif</option><option value="no">Nonaktif</option></select></label></div><div className="modal-foot"><button type="button" className="btn-outline" onClick={()=>setModal(false)}>Batal</button><button className="btn-primary" disabled={busy}>{busy?'Menyimpan...':'Simpan Kupon'}</button></div></form></div>}
  </DashboardShell>
}
