import { Edit3, Plus, Search, Trash2, X } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import DashboardShell from '../components/DashboardShell'
import QuillEditor from '../components/QuillEditor'
import { getOwnerContext, supabase, supabaseEnabled } from '../lib/supabase'

const empty={title:'',slug:'',excerpt:'',content:'',cover_image_url:'',author_name:'Admin',featured:false,status:true,published_at:''}
const slugify=s=>String(s||'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')
const localDate=v=>v?new Date(v).toLocaleDateString('id-ID'):'-'

export default function OwnerArticles(){
  const[rows,setRows]=useState([]),[storeId,setStoreId]=useState(''),[loading,setLoading]=useState(true),[q,setQ]=useState(''),[status,setStatus]=useState('all'),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(10),[modal,setModal]=useState(false),[form,setForm]=useState(empty),[editing,setEditing]=useState(null),[busy,setBusy]=useState(false)
  const load=async()=>{setLoading(true);try{if(!supabaseEnabled)return;const ctx=await getOwnerContext();if(!ctx.storeId)throw new Error('Store owner tidak ditemukan.');setStoreId(ctx.storeId);const{data,error}=await supabase.from('articles').select('*').eq('store_id',ctx.storeId).order('created_at',{ascending:false});if(error)throw error;setRows(data||[])}catch(e){alert(e.message)}finally{setLoading(false)}}
  useEffect(()=>{load()},[])
  const filtered=useMemo(()=>rows.filter(r=>(status==='all'||String(r.status)===status)&&(!q||`${r.title} ${r.slug} ${r.author_name||''}`.toLowerCase().includes(q.toLowerCase()))),[rows,q,status])
  const pages=Math.max(1,Math.ceil(filtered.length/pageSize)); const safePage=Math.min(page,pages); const visible=filtered.slice((safePage-1)*pageSize,safePage*pageSize)
  const openNew=()=>{setEditing(null);setForm({...empty,published_at:new Date().toISOString().slice(0,16)});setModal(true)}
  const openEdit=r=>{setEditing(r.id);setForm({...empty,...r,published_at:r.published_at?new Date(r.published_at).toISOString().slice(0,16):''});setModal(true)}
  const save=async e=>{e.preventDefault();setBusy(true);try{if(!storeId)throw new Error('Store ID tidak ditemukan.');const payload={store_id:storeId,title:form.title.trim(),slug:(form.slug||slugify(form.title)).trim(),excerpt:form.excerpt||null,content:form.content||null,cover_image_url:form.cover_image_url||null,author_name:form.author_name||'Admin',featured:!!form.featured,status:!!form.status,published_at:form.published_at?new Date(form.published_at).toISOString():null,updated_at:new Date().toISOString()};if(!payload.title)throw new Error('Judul wajib diisi.');if(editing){const{error}=await supabase.from('articles').update(payload).eq('id',editing);if(error)throw error}else{const{error}=await supabase.from('articles').insert(payload);if(error)throw error}setModal(false);await load()}catch(e){alert(e.message)}finally{setBusy(false)}}
  const remove=async r=>{if(!confirm(`Hapus artikel "${r.title}"?`))return;const{error}=await supabase.from('articles').delete().eq('id',r.id);if(error)return alert(error.message);load()}
  return <DashboardShell title="Artikel & Blog" subtitle="Kelola artikel yang tampil di homepage dan halaman blog."><div className="dash-panel table-panel"><div className="toolbar toolbar-pad"><div className="search-small"><Search/><input value={q} onChange={e=>{setQ(e.target.value);setPage(1)}} placeholder="Cari judul, slug, penulis..."/></div><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="all">Semua Status</option><option value="true">Published</option><option value="false">Draft</option></select><div className="toolbar-spacer"/><button className="btn-primary" onClick={openNew}><Plus size={16}/> Tambah Artikel</button></div><div className="responsive-table"><table><thead><tr><th>Artikel</th><th>Penulis</th><th>Publish</th><th>Status</th><th>Featured</th><th>Aksi</th></tr></thead><tbody>{loading?<tr><td colSpan="6" className="empty-cell">Memuat...</td></tr>:visible.length?visible.map(r=><tr key={r.id}><td><div className="table-product">{r.cover_image_url?<img src={r.cover_image_url} alt=""/>:<div className="table-thumb-placeholder">A</div>}<span><b>{r.title}</b><small>/{r.slug}</small></span></div></td><td>{r.author_name||'Admin'}</td><td>{localDate(r.published_at)}</td><td><span className={`status ${r.status?'ok':'off'}`}>{r.status?'Published':'Draft'}</span></td><td>{r.featured?'Ya':'-'}</td><td><div className="table-actions"><button onClick={()=>openEdit(r)} title="Edit"><Edit3/></button><button onClick={()=>remove(r)} title="Hapus"><Trash2/></button></div></td></tr>):<tr><td colSpan="6" className="empty-cell">Belum ada artikel.</td></tr>}</tbody></table></div><div className="pagination"><span>{filtered.length} artikel</span><select value={pageSize} onChange={e=>{setPageSize(Number(e.target.value));setPage(1)}}><option>10</option><option>25</option><option>50</option></select><button disabled={safePage<=1} onClick={()=>setPage(p=>p-1)}>‹</button><b>{safePage}/{pages}</b><button disabled={safePage>=pages} onClick={()=>setPage(p=>p+1)}>›</button></div></div>
  {modal&&<div className="modal-backdrop"><form className="admin-modal" onSubmit={save}><div className="admin-modal-head"><div><h2>{editing?'Edit Artikel':'Tambah Artikel'}</h2><p>Konten akan tampil di homepage dan halaman Artikel saat status Published.</p></div><button type="button" onClick={()=>setModal(false)}><X/></button></div><div className="form-grid"><label className="span2">Judul<input value={form.title} onChange={e=>setForm({...form,title:e.target.value,slug:editing?form.slug:slugify(e.target.value)})}/></label><label>Slug<input value={form.slug} onChange={e=>setForm({...form,slug:slugify(e.target.value)})}/></label><label>Penulis<input value={form.author_name||''} onChange={e=>setForm({...form,author_name:e.target.value})}/></label><label className="span2">Cover Image URL<input value={form.cover_image_url||''} onChange={e=>setForm({...form,cover_image_url:e.target.value})} placeholder="https://..."/></label><label className="span2">Ringkasan<textarea value={form.excerpt||''} onChange={e=>setForm({...form,excerpt:e.target.value})}/></label><label className="span2">Isi Artikel<QuillEditor value={form.content||''} onChange={content=>setForm(current=>({...current,content}))} placeholder="Tulis artikel di sini..."/><small>Rich text editor: heading, bold, italic, underline, list, warna, hyperlink, gambar URL, alignment, blockquote, dan clear format.</small></label><label>Tanggal Publish<input type="datetime-local" value={form.published_at||''} onChange={e=>setForm({...form,published_at:e.target.value})}/></label><div className="check-row"><label><input type="checkbox" checked={!!form.status} onChange={e=>setForm({...form,status:e.target.checked})}/> Published</label><label><input type="checkbox" checked={!!form.featured} onChange={e=>setForm({...form,featured:e.target.checked})}/> Featured</label></div></div><div className="modal-foot"><button type="button" className="btn-secondary" onClick={()=>setModal(false)}>Batal</button><button className="btn-primary" disabled={busy}>{busy?'Menyimpan...':'Simpan Artikel'}</button></div></form></div>}
  </DashboardShell>
}
