import DashboardShell from '../components/DashboardShell'
import { useEffect, useMemo, useState } from 'react'
import { getOwnerContext, supabase, supabaseEnabled } from '../lib/supabase'
import { Edit3, KeyRound, Plus, Search, ShieldCheck, Trash2, UserCheck, UserX, X } from 'lucide-react'

const empty={name:'',email:'',phone:'',role:'cashier',active:true,permissions:{pos:true,orders:true,products:false,inventory:false,reports:false}}
const perms=[['pos','Kasir POS'],['orders','Pesanan'],['products','Produk & Konten'],['inventory','Inventory'],['reports','Laporan']]
export default function OwnerStaff(){
  const[data,setData]=useState([]);const[storeId,setStoreId]=useState('');const[search,setSearch]=useState('');const[page,setPage]=useState(1);const[size,setSize]=useState(10);const[modal,setModal]=useState(false);const[form,setForm]=useState(empty);const[busy,setBusy]=useState(false)
  const load=async()=>{if(!supabaseEnabled)return;const ctx=await getOwnerContext();if(!ctx.storeId)throw new Error('Store tidak ditemukan.');setStoreId(ctx.storeId);const{data,error}=await supabase.from('store_staff').select('*').eq('store_id',ctx.storeId).order('created_at',{ascending:false});if(error)throw error;setData(data||[])}
  useEffect(()=>{load().catch(e=>alert(e.message))},[])
  const filtered=useMemo(()=>data.filter(x=>!search||`${x.name||''} ${x.email||''} ${x.phone||''}`.toLowerCase().includes(search.toLowerCase())),[data,search]);const pages=Math.max(1,Math.ceil(filtered.length/size));const rows=filtered.slice((page-1)*size,page*size)
  const invoke=async body=>{const{data,error}=await supabase.functions.invoke('staff-invite',{body});if(error)throw error;if(!data?.ok)throw new Error(data?.message||'Proses staff gagal');return data}
  const save=async e=>{e.preventDefault();setBusy(true);try{if(!form.email)throw new Error('Email staff wajib diisi.');const result=await invoke({action:'invite',name:form.name,email:form.email,phone:form.phone,role:form.role,permissions:form.permissions,active:form.active!==false,redirect_origin:window.location.origin});alert(result.message);await load();setModal(false)}catch(e){alert(e.message)}finally{setBusy(false)}}
  const resend=async x=>{setBusy(true);try{const result=await invoke({action:'invite',name:x.name,email:x.email,phone:x.phone,role:x.role,permissions:x.permissions,redirect_origin:window.location.origin});alert(result.message);await load()}catch(e){alert(e.message)}finally{setBusy(false)}}
  const setActive=async x=>{setBusy(true);try{const result=await invoke({action:'status',staff_id:x.id,active:!x.active});alert(result.message);await load()}catch(e){alert(e.message)}finally{setBusy(false)}}
  const del=async x=>{if(!confirm(`Hapus staff ${x.name} dan akses login-nya?`))return;setBusy(true);try{const result=await invoke({action:'delete',staff_id:x.id});alert(result.message);await load()}catch(e){alert(e.message)}finally{setBusy(false)}}
  const togglePerm=p=>setForm({...form,permissions:{...(form.permissions||{}),[p]:!(form.permissions||{})[p]}})
  return <DashboardShell title="Manajemen Kasir & Staff" subtitle="Undang akun staff, atur role, permission, dan akses login untuk satu toko.">
    <div className="module-hero tone-staff"><div><span>STAFF ACCESS</span><h2>Kasir punya akun sendiri, owner tetap pegang kontrol</h2><p>Undangan dikirim melalui Supabase Auth. Nonaktifkan staff kapan saja tanpa berbagi password owner.</p></div><div className="module-hero-icon"><ShieldCheck/></div></div>
    <div className="toolbar"><div className="search-small"><Search/><input placeholder="Cari nama / email / WA..." value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/></div><div className="toolbar-spacer"/><button className="btn-primary" onClick={()=>{setForm(empty);setModal(true)}}><Plus size={15}/>Undang Staff</button></div>
    <div className="dash-panel table-panel"><div className="responsive-table"><table><thead><tr><th>Staff</th><th>Role</th><th>Permission</th><th>Login</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><b>{x.name}</b><small style={{display:'block'}}>{x.email||x.phone||'-'}</small></td><td><span className="soft-pill">{x.role}</span></td><td>{Object.entries(x.permissions||{}).filter(([,v])=>v).map(([k])=>perms.find(p=>p[0]===k)?.[1]||k).join(', ')||'-'}</td><td><span className={`status ${x.auth_user_id?'ok':'warn'}`}>{x.auth_user_id?'Terhubung':'Belum Invite'}</span></td><td><span className={`status ${x.active?'ok':'off'}`}>{x.active?'Aktif':'Nonaktif'}</span></td><td className="table-actions"><button title="Edit" onClick={()=>{setForm({...empty,...x,permissions:x.permissions||{}});setModal(true)}}><Edit3/></button>{!x.auth_user_id&&x.email&&<button title="Kirim invite" onClick={()=>resend(x)}><KeyRound/></button>}<button title={x.active?'Nonaktifkan':'Aktifkan'} onClick={()=>setActive(x)}>{x.active?<UserX/>:<UserCheck/>}</button><button title="Hapus" onClick={()=>del(x)}><Trash2/></button></td></tr>)}</tbody></table></div><div className="pagination"><span>{filtered.length} data</span><select value={size} onChange={e=>{setSize(Number(e.target.value));setPage(1)}}><option>10</option><option>25</option><option>50</option></select><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>←</button><b>{page}/{pages}</b><button disabled={page>=pages} onClick={()=>setPage(p=>p+1)}>→</button></div></div>
    {modal&&<div className="modal-backdrop"><form className="admin-modal" onSubmit={save}><div className="admin-modal-head"><div><h2>{form.id?'Edit':'Undang'} Staff</h2><p>{form.id?'Ubah role dan hak akses operasional.':'Email akan menerima link untuk membuat password.'}</p></div><button type="button" onClick={()=>setModal(false)}><X/></button></div><div className="form-grid"><label>Nama<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Role<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="cashier">Kasir</option><option value="manager">Manager</option><option value="inventory">Inventory</option><option value="admin">Admin Toko</option></select></label><label>Email<input required={!form.id} disabled={!!form.auth_user_id} type="email" value={form.email||''} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>WhatsApp<input value={form.phone||''} onChange={e=>setForm({...form,phone:e.target.value})}/></label><div className="span2 form-section"><h2>Permission Menu</h2><div className="permission-grid">{perms.map(([p,label])=><label className="permission-card" key={p}><input type="checkbox" checked={!!(form.permissions||{})[p]} onChange={()=>togglePerm(p)}/><span><b>{label}</b><small>{p==='pos'?'Transaksi kasir':p==='orders'?'Proses pesanan':p==='products'?'Produk, kategori, artikel & promo':p==='inventory'?'Stok, ongkir & pembayaran':'Profit report'}</small></span></label>)}</div></div>{form.id&&<label className="span2">Status<select value={form.active?'yes':'no'} onChange={e=>setForm({...form,active:e.target.value==='yes'})}><option value="yes">Aktif</option><option value="no">Nonaktif</option></select></label>}</div><div className="modal-foot"><button type="button" className="btn-outline" onClick={()=>setModal(false)}>Batal</button><button className="btn-primary" disabled={busy}>{busy?'Memproses...':form.id?'Simpan Staff':'Kirim Undangan'}</button></div></form></div>}
  </DashboardShell>
}
