import DashboardShell from '../components/DashboardShell'
import { useEffect, useMemo, useState } from 'react'
import { getOwnerContext, supabase, supabaseEnabled } from '../lib/supabase'
import { Edit3, ExternalLink, Plus, Search, Trash2, X } from 'lucide-react'

const empty={title:'',category:'Umum',video_url:'',description:'',sort_order:0,active:true}
export default function OwnerGuides(){
  const[data,setData]=useState([]);const[storeId,setStoreId]=useState('');const[search,setSearch]=useState('');const[page,setPage]=useState(1);const[size,setSize]=useState(10);const[modal,setModal]=useState(false);const[form,setForm]=useState(empty);const[busy,setBusy]=useState(false)
  const load=async()=>{if(!supabaseEnabled)return;const ctx=await getOwnerContext();if(!ctx.storeId)throw new Error('Store tidak ditemukan.');setStoreId(ctx.storeId);const{data,error}=await supabase.from('video_guides').select('*').eq('store_id',ctx.storeId).order('sort_order').order('created_at',{ascending:false});if(error)throw error;setData(data||[])}
  useEffect(()=>{load().catch(e=>alert(e.message))},[])
  const filtered=useMemo(()=>data.filter(x=>!search||`${x.title||''} ${x.category||''}`.toLowerCase().includes(search.toLowerCase())),[data,search]);const pages=Math.max(1,Math.ceil(filtered.length/size));const rows=filtered.slice((page-1)*size,page*size)
  const save=async e=>{e.preventDefault();setBusy(true);try{const payload={store_id:storeId,title:form.title.trim(),category:form.category||'Umum',video_url:form.video_url.trim(),description:form.description||null,sort_order:Number(form.sort_order||0),active:!!form.active};if(form.id){const{error}=await supabase.from('video_guides').update(payload).eq('id',form.id).eq('store_id',storeId);if(error)throw error}else{const{error}=await supabase.from('video_guides').insert(payload);if(error)throw error}await load();setModal(false)}catch(e){alert(e.message)}finally{setBusy(false)}}
  const del=async x=>{if(!confirm(`Hapus video ${x.title}?`))return;const{error}=await supabase.from('video_guides').delete().eq('id',x.id).eq('store_id',storeId);if(error)alert(error.message);else load().catch(e=>alert(e.message))}
  return <DashboardShell title="Video Panduan" subtitle="Panduan operasional yang bisa disesuaikan untuk masing-masing toko white-label.">
    <div className="toolbar"><div className="search-small"><Search/><input placeholder="Cari judul / kategori..." value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/></div><div className="toolbar-spacer"/><button className="btn-primary" onClick={()=>{setForm(empty);setModal(true)}}><Plus size={15}/>Tambah Video</button></div>
    <div className="dash-panel table-panel"><div className="responsive-table"><table><thead><tr><th>Judul</th><th>Kategori</th><th>Urutan</th><th>Status</th><th>Link</th><th></th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><b>{x.title}</b><small style={{display:'block'}}>{x.description||''}</small></td><td><span className="soft-pill">{x.category}</span></td><td>{x.sort_order}</td><td><span className={`status ${x.active?'ok':'off'}`}>{x.active?'Aktif':'Nonaktif'}</span></td><td><a className="btn-outline" href={x.video_url} target="_blank" rel="noreferrer"><ExternalLink size={13}/>Buka</a></td><td className="table-actions"><button onClick={()=>{setForm({...empty,...x});setModal(true)}}><Edit3/></button><button onClick={()=>del(x)}><Trash2/></button></td></tr>)}</tbody></table></div><div className="pagination"><span>{filtered.length} data</span><select value={size} onChange={e=>{setSize(Number(e.target.value));setPage(1)}}><option>10</option><option>25</option><option>50</option></select><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>←</button><b>{page}/{pages}</b><button disabled={page>=pages} onClick={()=>setPage(p=>p+1)}>→</button></div></div>
    {modal&&<div className="modal-backdrop"><form className="admin-modal" onSubmit={save}><div className="admin-modal-head"><div><h2>{form.id?'Edit':'Tambah'} Video Panduan</h2><p>YouTube, Vimeo atau URL video lainnya.</p></div><button type="button" onClick={()=>setModal(false)}><X/></button></div><div className="form-grid"><label className="span2">Judul<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Kategori<input value={form.category||''} onChange={e=>setForm({...form,category:e.target.value})}/></label><label>Urutan<input type="number" value={form.sort_order} onChange={e=>setForm({...form,sort_order:e.target.value})}/></label><label className="span2">Video URL<input required value={form.video_url} onChange={e=>setForm({...form,video_url:e.target.value})}/></label><label className="span2">Deskripsi<textarea value={form.description||''} onChange={e=>setForm({...form,description:e.target.value})}/></label><label className="span2">Status<select value={form.active?'yes':'no'} onChange={e=>setForm({...form,active:e.target.value==='yes'})}><option value="yes">Aktif</option><option value="no">Nonaktif</option></select></label></div><div className="modal-foot"><button type="button" className="btn-outline" onClick={()=>setModal(false)}>Batal</button><button className="btn-primary" disabled={busy}>{busy?'Menyimpan...':'Simpan Video'}</button></div></form></div>}
  </DashboardShell>
}
