import DashboardShell from '../components/DashboardShell'
import { useEffect, useMemo, useState } from 'react'
import { getOwnerContext, supabase, supabaseEnabled } from '../lib/supabase'
import { rupiah } from '../lib/format'
import { Eye, Search, X } from 'lucide-react'

export default function OwnerOrders(){
  const[data,setData]=useState([]);const[storeId,setStoreId]=useState('');const[search,setSearch]=useState('');const[status,setStatus]=useState('all');const[payment,setPayment]=useState('all');const[page,setPage]=useState(1);const[size,setSize]=useState(10);const[detail,setDetail]=useState(null);const[busy,setBusy]=useState('')
  const load=async()=>{if(!supabaseEnabled)return;const ctx=await getOwnerContext();if(!ctx.storeId)throw new Error('Store tidak ditemukan.');setStoreId(ctx.storeId);const{data,error}=await supabase.from('orders').select('*,customer:customers(name,phone,email,address),order_items(id,product_name,qty,price,subtotal)').eq('store_id',ctx.storeId).order('created_at',{ascending:false}).limit(1000);if(error)throw error;setData(data||[])}
  useEffect(()=>{load().catch(e=>alert(e.message))},[])
  const filtered=useMemo(()=>data.filter(o=>(status==='all'||o.status===status)&&(payment==='all'||o.payment_status===payment)&&(!search||`${o.order_number||''} ${o.customer?.name||''} ${o.customer?.phone||''}`.toLowerCase().includes(search.toLowerCase()))),[data,search,status,payment]);const pages=Math.max(1,Math.ceil(filtered.length/size));const rows=filtered.slice((page-1)*size,page*size)
  const update=async(o,patch)=>{setBusy(o.id);try{const{error}=await supabase.from('orders').update(patch).eq('id',o.id).eq('store_id',storeId);if(error)throw error;await load();if(detail?.id===o.id)setDetail({...detail,...patch})}catch(e){alert(e.message)}finally{setBusy('')}}
  return <DashboardShell title="Pesanan Masuk" subtitle="Kelola order toko online dan Kasir POS dari satu tabel.">
    <div className="toolbar"><div className="search-small"><Search/><input placeholder="Cari order / customer / WA..." value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/></div><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="all">Semua status</option><option value="pending">Pending</option><option value="processing">Processing</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select><select value={payment} onChange={e=>{setPayment(e.target.value);setPage(1)}}><option value="all">Semua payment</option><option value="unpaid">Unpaid</option><option value="paid">Paid</option><option value="refunded">Refunded</option></select></div>
    <div className="dash-panel table-panel"><div className="responsive-table"><table><thead><tr><th>Order</th><th>Customer</th><th>Source</th><th>Status</th><th>Payment</th><th>Total</th><th>Tanggal</th><th></th></tr></thead><tbody>{rows.map(o=><tr key={o.id}><td><b>{o.order_number||o.id.slice(0,8)}</b></td><td><b>{o.customer?.name||'-'}</b><small style={{display:'block'}}>{o.customer?.phone||''}</small></td><td><span className="soft-pill">{o.source||'online'}</span></td><td><select disabled={busy===o.id} value={o.status||'pending'} onChange={e=>update(o,{status:e.target.value})}><option>pending</option><option>processing</option><option>completed</option><option>cancelled</option></select></td><td><select disabled={busy===o.id} value={o.payment_status||'unpaid'} onChange={e=>update(o,{payment_status:e.target.value})}><option>unpaid</option><option>paid</option><option>refunded</option></select></td><td><b>{rupiah(o.total_amount)}</b></td><td>{new Date(o.created_at).toLocaleString('id-ID')}</td><td className="table-actions"><button onClick={()=>setDetail(o)}><Eye/></button></td></tr>)}</tbody></table></div><div className="pagination"><span>{filtered.length} data</span><select value={size} onChange={e=>{setSize(Number(e.target.value));setPage(1)}}><option>10</option><option>25</option><option>50</option></select><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>←</button><b>{page}/{pages}</b><button disabled={page>=pages} onClick={()=>setPage(p=>p+1)}>→</button></div></div>
    {detail&&<div className="modal-backdrop"><div className="admin-modal"><div className="admin-modal-head"><div><h2>Detail {detail.order_number}</h2><p>{detail.customer?.name||'Customer'} • {detail.payment_method||'-'}</p></div><button onClick={()=>setDetail(null)}><X/></button></div><div style={{padding:20}}><div className="inventory-summary"><div><span>Status</span><strong>{detail.status}</strong></div><div><span>Payment</span><strong>{detail.payment_status}</strong></div><div><span>Total</span><strong>{rupiah(detail.total_amount)}</strong></div></div><div className="dash-panel table-panel"><div className="responsive-table"><table><thead><tr><th>Produk</th><th>Qty</th><th>Harga</th><th>Subtotal</th></tr></thead><tbody>{(detail.order_items||[]).map(i=><tr key={i.id}><td>{i.product_name}</td><td>{i.qty}</td><td>{rupiah(i.price)}</td><td>{rupiah(i.subtotal)}</td></tr>)}</tbody></table></div></div>{detail.notes&&<div className="module-note" style={{marginTop:12}}>Catatan: {detail.notes}</div>}</div></div></div>}
  </DashboardShell>
}
