import { appConfirm } from '../lib/appDialog'
import DashboardShell from '../components/DashboardShell'
import { useEffect, useMemo, useState } from 'react'
import { getOwnerContext, supabase, supabaseEnabled } from '../lib/supabase'
import { rupiah } from '../lib/format'
import { Edit3, Plus, Search, Settings2, Trash2, Truck, X } from 'lucide-react'
import { Link } from 'react-router-dom'

const empty={name:'',area:'',price:0,enabled:true}
export default function OwnerShipping(){
  const[data,setData]=useState([]);const[storeId,setStoreId]=useState('');const[search,setSearch]=useState('');const[page,setPage]=useState(1);const[size,setSize]=useState(10);const[modal,setModal]=useState(false);const[form,setForm]=useState(empty);const[busy,setBusy]=useState(false)
  const load=async()=>{if(!supabaseEnabled)return;const ctx=await getOwnerContext();if(!ctx.storeId)throw new Error('Store tidak ditemukan.');setStoreId(ctx.storeId);const{data,error}=await supabase.from('shipping_settings').select('*').eq('store_id',ctx.storeId).order('created_at',{ascending:false});if(error)throw error;setData(data||[])}
  useEffect(()=>{load().catch(e=>alert(e.message))},[])
  const filtered=useMemo(()=>data.filter(x=>!search||`${x.name||''} ${x.area||''}`.toLowerCase().includes(search.toLowerCase())),[data,search]);const pages=Math.max(1,Math.ceil(filtered.length/size));const rows=filtered.slice((page-1)*size,page*size)
  const save=async e=>{e.preventDefault();setBusy(true);try{const payload={store_id:storeId,name:form.name.trim(),area:form.area||null,price:Number(form.price||0),enabled:!!form.enabled};if(form.id){const{error}=await supabase.from('shipping_settings').update(payload).eq('id',form.id).eq('store_id',storeId);if(error)throw error}else{const{error}=await supabase.from('shipping_settings').insert(payload);if(error)throw error}await load();setModal(false)}catch(e){alert(e.message)}finally{setBusy(false)}}
  const del=async x=>{if(!(await appConfirm(`Hapus ongkir ${x.name}?`)))return;const{error}=await supabase.from('shipping_settings').delete().eq('id',x.id).eq('store_id',storeId);if(error)alert(error.message);else load().catch(e=>alert(e.message))}
  return <DashboardShell title="Pengaturan Ongkir" subtitle="Kelola ongkir manual untuk satu toko, atau aktifkan RajaOngkir dari Integration Hub.">
    <div className="module-hero tone-shipping"><div><span>SHIPPING CENTER</span><h2>Ongkir manual + RajaOngkir dalam satu alur</h2><p>Gunakan tarif manual untuk pickup/area tertentu, atau sambungkan RajaOngkir untuk kalkulasi checkout berdasarkan tujuan dan berat.</p><Link className="hero-inline-action" to="/owner/integrations"><Settings2/> Atur RajaOngkir</Link></div><div className="module-hero-icon"><Truck/></div></div>
    <div className="toolbar"><div className="search-small"><Search/><input placeholder="Cari nama / area..." value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/></div><div className="toolbar-spacer"/><button className="btn-primary" onClick={()=>{setForm(empty);setModal(true)}}><Plus size={15}/>Tambah Ongkir</button></div>
    <div className="dash-panel table-panel"><div className="responsive-table"><table><thead><tr><th>Nama</th><th>Area</th><th>Harga</th><th>Status</th><th></th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><b>{x.name}</b></td><td>{x.area||'-'}</td><td><b>{rupiah(x.price)}</b></td><td><span className={`status ${x.enabled?'ok':'off'}`}>{x.enabled?'Aktif':'Nonaktif'}</span></td><td className="table-actions"><button onClick={()=>{setForm({...empty,...x});setModal(true)}}><Edit3/></button><button onClick={()=>del(x)}><Trash2/></button></td></tr>)}</tbody></table></div><div className="pagination"><span>{filtered.length} data</span><select value={size} onChange={e=>{setSize(Number(e.target.value));setPage(1)}}><option>10</option><option>25</option><option>50</option></select><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>←</button><b>{page}/{pages}</b><button disabled={page>=pages} onClick={()=>setPage(p=>p+1)}>→</button></div></div>
    {modal&&<div className="modal-backdrop"><form className="admin-modal" onSubmit={save}><div className="admin-modal-head"><div><h2>{form.id?'Edit':'Tambah'} Ongkir</h2><p>Contoh: Jabodetabek / Bogor / Pickup.</p></div><button type="button" onClick={()=>setModal(false)}><X/></button></div><div className="form-grid"><label>Nama Layanan<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Area<input value={form.area||''} onChange={e=>setForm({...form,area:e.target.value})}/></label><label>Harga<input type="number" min="0" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label><label><span>Status</span><select value={form.enabled?'yes':'no'} onChange={e=>setForm({...form,enabled:e.target.value==='yes'})}><option value="yes">Aktif</option><option value="no">Nonaktif</option></select></label></div><div className="modal-foot"><button type="button" className="btn-outline" onClick={()=>setModal(false)}>Batal</button><button className="btn-primary" disabled={busy}>{busy?'Menyimpan...':'Simpan Ongkir'}</button></div></form></div>}
  </DashboardShell>
}
