import DashboardShell from '../components/DashboardShell'
import { useEffect, useMemo, useState } from 'react'
import { getOwnerContext, supabase, supabaseEnabled } from '../lib/supabase'
import { Edit3, Plus, Search, Trash2, X } from 'lucide-react'

const empty={name:'',email:'',phone:'',role:'cashier',active:true,permissions:{pos:true,orders:true,products:false,inventory:false,reports:false}}
const perms=['pos','orders','products','inventory','reports']
export default function OwnerStaff(){
  const[data,setData]=useState([]);const[storeId,setStoreId]=useState('');const[search,setSearch]=useState('');const[page,setPage]=useState(1);const[size,setSize]=useState(10);const[modal,setModal]=useState(false);const[form,setForm]=useState(empty);const[busy,setBusy]=useState(false)
  const load=async()=>{if(!supabaseEnabled)return;const ctx=await getOwnerContext();if(!ctx.storeId)throw new Error('Store tidak ditemukan.');setStoreId(ctx.storeId);const{data,error}=await supabase.from('store_staff').select('*').eq('store_id',ctx.storeId).order('created_at',{ascending:false});if(error)throw error;setData(data||[])}
  useEffect(()=>{load().catch(e=>alert(e.message))},[])
  const filtered=useMemo(()=>data.filter(x=>!search||`${x.name||''} ${x.email||''} ${x.phone||''}`.toLowerCase().includes(search.toLowerCase())),[data,search]);const pages=Math.max(1,Math.ceil(filtered.length/size));const rows=filtered.slice((page-1)*size,page*size)
  const save=async e=>{e.preventDefault();setBusy(true);try{const payload={store_id:storeId,name:form.name.trim(),email:form.email||null,phone:form.phone||null,role:form.role,active:!!form.active,permissions:form.permissions||{}};if(form.id){const{error}=await supabase.from('store_staff').update(payload).eq('id',form.id).eq('store_id',storeId);if(error)throw error}else{const{error}=await supabase.from('store_staff').insert(payload);if(error)throw error}await load();setModal(false)}catch(e){alert(e.message)}finally{setBusy(false)}}
  const del=async x=>{if(!confirm(`Hapus staff ${x.name}?`))return;const{error}=await supabase.from('store_staff').delete().eq('id',x.id).eq('store_id',storeId);if(error)alert(error.message);else load().catch(e=>alert(e.message))}
  const togglePerm=p=>setForm({...form,permissions:{...(form.permissions||{}),[p]:!(form.permissions||{})[p]}})
  return <DashboardShell title="Manajemen Kasir" subtitle="Kelola profil staff, role dan permission operasional per toko.">
    <div className="module-note">Registry staff dan permission sudah aktif. <b>Aktivasi login staff via Supabase Auth/invite</b> akan kita sambungkan di tahap auth staff berikutnya; data role dan permission ini sudah siap dipakai.</div>
    <div className="toolbar"><div className="search-small"><Search/><input placeholder="Cari nama / email / WA..." value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/></div><div className="toolbar-spacer"/><button className="btn-primary" onClick={()=>{setForm(empty);setModal(true)}}><Plus size={15}/>Tambah Staff</button></div>
    <div className="dash-panel table-panel"><div className="responsive-table"><table><thead><tr><th>Staff</th><th>Role</th><th>Permission</th><th>Auth</th><th>Status</th><th></th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><b>{x.name}</b><small style={{display:'block'}}>{x.email||x.phone||'-'}</small></td><td><span className="soft-pill">{x.role}</span></td><td>{Object.entries(x.permissions||{}).filter(([,v])=>v).map(([k])=>k).join(', ')||'-'}</td><td><span className={`status ${x.auth_user_id?'ok':'warn'}`}>{x.auth_user_id?'Terhubung':'Belum Invite'}</span></td><td><span className={`status ${x.active?'ok':'off'}`}>{x.active?'Aktif':'Nonaktif'}</span></td><td className="table-actions"><button onClick={()=>{setForm({...empty,...x,permissions:x.permissions||{}});setModal(true)}}><Edit3/></button><button onClick={()=>del(x)}><Trash2/></button></td></tr>)}</tbody></table></div><div className="pagination"><span>{filtered.length} data</span><select value={size} onChange={e=>{setSize(Number(e.target.value));setPage(1)}}><option>10</option><option>25</option><option>50</option></select><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>←</button><b>{page}/{pages}</b><button disabled={page>=pages} onClick={()=>setPage(p=>p+1)}>→</button></div></div>
    {modal&&<div className="modal-backdrop"><form className="admin-modal" onSubmit={save}><div className="admin-modal-head"><div><h2>{form.id?'Edit':'Tambah'} Staff</h2><p>Atur role dan akses menu.</p></div><button type="button" onClick={()=>setModal(false)}><X/></button></div><div className="form-grid"><label>Nama<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Role<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="cashier">Kasir</option><option value="manager">Manager</option><option value="inventory">Inventory</option><option value="admin">Admin Toko</option></select></label><label>Email<input type="email" value={form.email||''} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>WhatsApp<input value={form.phone||''} onChange={e=>setForm({...form,phone:e.target.value})}/></label><div className="span2 form-section"><h2>Permission</h2><div className="check-row">{perms.map(p=><label key={p}><input type="checkbox" checked={!!(form.permissions||{})[p]} onChange={()=>togglePerm(p)}/>{p}</label>)}</div></div><label className="span2">Status<select value={form.active?'yes':'no'} onChange={e=>setForm({...form,active:e.target.value==='yes'})}><option value="yes">Aktif</option><option value="no">Nonaktif</option></select></label></div><div className="modal-foot"><button type="button" className="btn-outline" onClick={()=>setModal(false)}>Batal</button><button className="btn-primary" disabled={busy}>{busy?'Menyimpan...':'Simpan Staff'}</button></div></form></div>}
  </DashboardShell>
}
