import { appConfirm } from '../lib/appDialog'
import DashboardShell from '../components/DashboardShell'
import { useEffect, useMemo, useState } from 'react'
import { getOwnerContext, supabase, supabaseEnabled } from '../lib/supabase'
import { Edit3, Plus, Search, Trash2, X } from 'lucide-react'

const empty={name:'',image_url:'',type:'physical',sort_order:0,status:true}

export default function OwnerCategories(){
  const[data,setData]=useState([]);const[storeId,setStoreId]=useState('');const[modal,setModal]=useState(false);const[form,setForm]=useState(empty);const[search,setSearch]=useState('');const[type,setType]=useState('all');const[page,setPage]=useState(1);const[size,setSize]=useState(10);const[busy,setBusy]=useState(false)
  const load=async()=>{if(!supabaseEnabled)return;const ctx=await getOwnerContext();if(!ctx.storeId)throw new Error('Store tidak ditemukan.');setStoreId(ctx.storeId);const{data,error}=await supabase.from('categories').select('*').eq('store_id',ctx.storeId).order('sort_order').order('name');if(error)throw error;setData(data||[])}
  useEffect(()=>{load().catch(e=>alert(e.message))},[])
  const filtered=useMemo(()=>data.filter(x=>(type==='all'||x.type===type)&&(!search||x.name.toLowerCase().includes(search.toLowerCase()))),[data,search,type]);const pages=Math.max(1,Math.ceil(filtered.length/size));const rows=filtered.slice((page-1)*size,page*size)
  const open=x=>{setForm(x?{...empty,...x}:empty);setModal(true)}
  const save=async e=>{e.preventDefault();setBusy(true);try{const payload={store_id:storeId,name:form.name.trim(),image_url:form.image_url||null,type:form.type,sort_order:Number(form.sort_order||0),status:!!form.status};if(form.id){const{error}=await supabase.from('categories').update(payload).eq('id',form.id).eq('store_id',storeId);if(error)throw error}else{const{error}=await supabase.from('categories').insert(payload);if(error)throw error}await load();setModal(false)}catch(err){alert(err.message)}finally{setBusy(false)}}
  const del=async x=>{if(!(await appConfirm(`Hapus kategori ${x.name}?`)))return;const{error}=await supabase.from('categories').delete().eq('id',x.id).eq('store_id',storeId);if(error)alert(error.message);else load().catch(e=>alert(e.message))}
  return <DashboardShell title="Kategori Produk" subtitle="Pisahkan kategori produk fisik dan digital agar storefront lebih rapi.">
    <div className="toolbar"><div className="search-small"><Search/><input placeholder="Cari kategori..." value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/></div><select value={type} onChange={e=>{setType(e.target.value);setPage(1)}}><option value="all">Semua tipe</option><option value="physical">Produk Fisik</option><option value="digital">Produk Digital</option><option value="pulsa_data">Pulsa/Data</option><option value="pln_token">Token PLN</option></select><div className="toolbar-spacer"/><button className="btn-primary" onClick={()=>open()}><Plus size={15}/>Tambah Kategori</button></div>
    <div className="dash-panel table-panel"><div className="responsive-table"><table><thead><tr><th>Kategori</th><th>Tipe</th><th>Urutan</th><th>Status</th><th></th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><div className="table-product">{x.image_url?<img src={x.image_url}/>:<div className="table-thumb-placeholder">K</div>}<div><b>{x.name}</b><small>{x.image_url?'Image URL aktif':'Tanpa gambar'}</small></div></div></td><td><span className="soft-pill">{x.type}</span></td><td>{x.sort_order}</td><td><span className={`status ${x.status?'ok':'off'}`}>{x.status?'Aktif':'Nonaktif'}</span></td><td className="table-actions"><button onClick={()=>open(x)}><Edit3/></button><button onClick={()=>del(x)}><Trash2/></button></td></tr>)}</tbody></table></div><div className="pagination"><span>{filtered.length} data</span><select value={size} onChange={e=>{setSize(Number(e.target.value));setPage(1)}}><option>10</option><option>25</option><option>50</option></select><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>←</button><b>{page}/{pages}</b><button disabled={page>=pages} onClick={()=>setPage(p=>p+1)}>→</button></div></div>
    {modal&&<div className="modal-backdrop"><form className="admin-modal" onSubmit={save}><div className="admin-modal-head"><div><h2>{form.id?'Edit':'Tambah'} Kategori</h2><p>Kategori untuk toko ini dan storefront publik.</p></div><button type="button" onClick={()=>setModal(false)}><X/></button></div><div className="form-grid"><label className="span2">Nama Kategori<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="span2">Image URL<input value={form.image_url||''} onChange={e=>setForm({...form,image_url:e.target.value})}/></label><label>Tipe<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="physical">Physical</option><option value="digital">Digital</option><option value="pulsa_data">Pulsa / Data</option><option value="pln_token">Token PLN</option></select></label><label>Urutan<input type="number" value={form.sort_order} onChange={e=>setForm({...form,sort_order:e.target.value})}/></label><label className="span2"><input type="checkbox" checked={!!form.status} onChange={e=>setForm({...form,status:e.target.checked})}/> Aktif</label></div><div className="modal-foot"><button type="button" className="btn-outline" onClick={()=>setModal(false)}>Batal</button><button className="btn-primary" disabled={busy}>{busy?'Menyimpan...':'Simpan Kategori'}</button></div></form></div>}
  </DashboardShell>
}
